version: '3.8'

services:
  api:
    build: . # Constrói imagem a partir do Dockerfile
    container_name: escola_api
    restart: always # Tenta reiniciar o container em caso de falha
    
    # Mapeia a porta
    ports:
      - "5000:5000"
      
    # Cria um volume persistente para armazenar o arquivo SQLite
    volumes:
      - .:/usr/src/app 
      # Mapeia a pasta 'instance' com o .db
      - api_data:/usr/src/app/instance 

    environment:
      # Variáveis de ambiente
      - FLASK_APP=run.py
      
    # O comando de inicialização
    command: ["gunicorn", "--bind", "0.0.0.0:5000", "run:app"]


volumes:
  api_data: